### ISSUE TITLE
boolean flags don't pass correctly

### ISSUE THREAD

**Issue by ianwremmel** [tusbar/grunt-subgrunt#19] opened 2015-11-09 21:23 UTC
if I run 

```
grunt subgrunt:mytask --coverage=true
```

and the tasks in `mytask` are `['test', 'build']`

then subgrunt runs 
```
grunt --coverage test build
```
in `./mytask` which grunt interprets as 

```
grunt --coverage=test build
```

**Comment by ianwremmel** [comment] 2015-11-09 21:29
I solved it by using 

```
grunt --coverage=TRUE test build
```

but that's not an immediately obvious solution.

**Comment by tusbar** [comment] 2015-11-10 10:31
Hey @ianwremmel thank you for reporting this, working on a fix.

**Comment by tusbar** [comment] 2015-11-10 14:48
@ianwremmel fix released as 1.1.0 on npm.

**Comment by ianwremmel** [comment] 2015-11-10 15:27
@tusbar, thanks for the quick response. I haven't had a chance to test it yet, but I think there still might be a gap in your test scenario:

I'm pretty sure 
```
grunt mytask --coverage=true --xunit=true
```

will translate to 
```
grunt test build --coverage=--xunit=true
```

and therefore be interpreted as 

```
grunt test build --coverage=true
```

I'll attempt to test it out today and report back. Again, thanks!

**Comment by tusbar** [comment] 2015-11-10 16:02
@ianwremmel I see, it’s worse than I thought.

The issue seems to be with how `grunt` itself parses command line options

`grunt task --foo --bar` is interpreted as `grunt task --foo=--bar`

The issue is that [`grunt.option.flags()`](http://gruntjs.com/api/grunt.option#grunt.option.flags) returns a modified version of the arguments (`--foo=true` is transformed into `--foo`).

So when passing the arguments back to `grunt`, it is failing of course.

There’s a dirty hack we could do: check whether the option is a boolean option and add `=true` to each of those. Unless there’s a way to retrieve the original argument list.

Will investigate.

**Comment by ianwremmel** [comment] 2015-11-10 16:28
Nice, thanks for finding that. (I ran into similar issues with grunt concurrent six months ago, but never managed to find that issue). I'll give nopt-grunt-fix a try.

**Closed** 2016-01-05 15:20 UTC
